Fix release (hopefully), upgrading cli/gh-extension-precompile to v2
Before this fix, last release (v1.5.5) failed:

	cli/gh-extension-precompile@v1

	android/amd64 requires external (cgo) linking, but cgo is not enabled
	Error: Process completed with exit code 1.

https://github.com/nicokosi/gh-collab-scanner/actions/runs/18896702349/job/53935712648