Revert "Run CI and release with Go 1.22 🆙"
Try to fix release failure, downgrading Go to 1.21. 🤷

cli/gh-extension-precompile@v1 fails on out-of-the-box Ubuntu:

            android/amd64 requires external (cgo) linking, but cgo is not enabled
            Error: Process completed with exit code 1.

I failed activating CGO:

            # runtime/cgo
            gcc_android.c:6:10: fatal error: android/log.h: No such file or director
                6 | #include <android/log.h>
                  |          ^~~~~~~~~~~~~~~
            compilation terminated.

Release also failed	on Windows:

	Runner Image
	  Image: windows-2022

	Run cli/gh-extension-precompile@v1
	go: downloading github.com/rivo/uniseg v0.4.4
	android/amd64 requires external (cgo) linking, but cgo is not enabled
	Error: Process completed with exit code 1.

This reverts commit 4c052b044903409d80a02037d59383111d7988c7.