Try releasing on Windows 🤞
Because cli/gh-extension-precompile@v1 fails on out-of-the-box Ubuntu:

	android/amd64 requires external (cgo) linking, but cgo is not enabled
	Error: Process completed with exit code 1.

And I failed activating CGO:

	# runtime/cgo
	gcc_android.c:6:10: fatal error: android/log.h: No such file or directory
	    6 | #include <android/log.h>
	      |          ^~~~~~~~~~~~~~~
	compilation terminated.